name: Schedule-task 
on:
  # schedule:
  #   - cron: "0 15 * * *" # run once everday at day at 3:00 PM
  workflow_dispatch:  # manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email script
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: python send_email.py # run the script to send email